apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kaniko-workspace
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/pv/pv-kaniko"
